# name = input('Enter your name:')
# print(name)
# print('What is your name?')
# name = input()
# print(name)
# x = input('Enter a number: ')
# print(type(x))
# x = 5
# print('The number is ' + str(x))
# from datetime import date
# date.today()
# print(date.today())
# print("Today date is:"+str(date.today()))
# print("Welcome to the greeter program")
# name = input("Enter your name: ")
# print("Greetings " + name)
# print("calculator program")
# first_number = input("first number: ")
# second_number = input("second number: ")
# print(int(first_number) + int(second_number))
# addition = (23 + 78)
# print(addition)
# print (abs(39 - 16))
# print (floor(16.4))
# from math import ceil, floor
# kaif1 = ceil(12.5)
# print(kaif1)
# kaif2 = floor(12.5)
# print(kaif2)
Demo_int =int('218')
print(Demo_int)
Demo_float =float('289')
print(Demo_float) 